### ISSUE TITLE
Features roadmap

### ISSUE THREAD

**Issue by MasonProtter** [tshort/StaticCompiler.jl#59]
- [ ] Support storing and relocation of global variables
- [ ] Support for linking binaries to julia's runtime
- [x] Support Windows. (Help wanted!)
- [ ] Interfaces and tests for cross compilation

**Comment by MasonProtter** [comment]
I'll add those to the checklist.

**Comment by vchuravy** [comment]
Cross-compilation on the same OS is feasible, e.g. Linux to Linux, but cross-compilation across OS's is tricky since people love to do: `@statis if Sys.iswindows()`

**Comment by AriMKatz** [comment]
out of curiosity, how  hard would WASM compilation be? Just setting in LLVM or something else? 

I'd imagine could be straightforward for full static code. Otherwise, we could maybe compile the runtime to wasm. Python does that for the entire interpreter.  Or is that better as  some sort of plugin system or dependent package? 

cc: @fonsp

**Comment by AriMKatz** [comment]
Yea, does seem dicey...on the other hand @keno got all of Julia to compile to WASM here (with caveats): https://github.com/Keno/julia-wasm and that seems even dicey-er.  So maybe it's not as bad as we think and there could be some code or lessons lifted from that effort.

**Comment by vchuravy** [comment]
@rhuffyhas been working on compiling libjulia to WASM

**Comment by fonsp** [comment]
> @rhuffy has been working on compiling libjulia to WASM

Awesome! How is the progress there?

**Comment by davidanthoff** [comment]
Is compiling standalone executable also something that might work with this? We would love to eventually ship the language server as a precompiled binary :)

**Comment by Seelengrab** [comment]
Maybe I'm going a little off the deep end here, but is targeting bare-metal (i.e., there is no OS) anything short of infeasible?

**Comment by MasonProtter** [comment]
Okay, so a lot has changed with version 0.6 (https://github.com/tshort/StaticCompiler.jl/pull/146) and a lot of stuff on that roadmap is no longer relevant or planned, so I've updated it. 

The package is now significantly simpler and more streamlined, so hopefully future work on it will be easier.
